version: 2

jobs:

  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Static typechecking
          command: make mypy
      - run:
          name: Run tests
          command: make test

  build-docs:
      docker:
        - image: python:3.7
      steps:
        - checkout
        - run:
            name: Install conda
            command: |
              wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
              bash ~/miniconda.sh -b -p $HOME/miniconda
              export PATH="$HOME/miniconda/bin:$PATH"
        - run:
            name: Install Python dependencies
            command: pip install -r requirements.txt
        - run:
            name: Install pandoc
            command: |
            source $HOME/miniconda/bin/activate
            conda install -c conda-forge pandoc=1.19
        - run:
            name: Build docs
            command: make build_docs
        - persist_to_workspace:
            root: doc/_build
            paths: html

workflows:
  version: 2
  build:
    jobs:
      - test
      - build-docs