version: 2

jobs:

  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/requirements_ci.txt -r requirements/requirements.txt
      - run:
          name: Lint code
          command: flake8 alibi
      - run:
          name: Static typechecking
          command: mypy alibi
      - run:
          name: Run tests
          command: pytest
          no_output_timeout: 30m

  build-docs:
      docker:
        - image: python:3.7
      steps:
        - checkout
        - run:
            name: Install conda
            command: |
              wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
              bash ~/miniconda.sh -b -p $HOME/miniconda
              export PATH="$HOME/miniconda/bin:$PATH"
              conda update conda
              conda create -n docs python=3.7
        - run:
            name: Install Python dependencies, pandoc and alibi
            command: |
              source $HOME/miniconda/bin/activate docs
              pip install -r requirements/requirements_ci.txt -r requirements/requirements.txt
              conda install -c conda-forge pandoc=1.19
              make install
        - run:
            name: Build docs
            command: |
              source $HOME/miniconda/bin/activate docs
              make build_docs
        - persist_to_workspace:
            root: doc/_build
            paths: html

workflows:
  version: 2
  build:
    jobs:
      - test
      - build-docs
