dataset: adult

# Example of configuring a random forest classifier
clf-config:
  name: rf
  n_esimators: 50
  seed: 0

# Example of configuring a AnchorTabular explainer
expln-config:
  type: tabular
  threshold: 0.95
  disc_perc: !!python/tuple [25, 50, 75]
  parallel: false
  chunksize: 1
  ncpus: 2
  verbose: false
  seed: 0

# Experiment settings
exp-settings:
  n_runs: 100
  instance_idx: 6
  ckpt_dir: /home/alex/git/work_experiments/VectorisedBenchmark
  ckpt: Example2TestExperimentScript.pkl
  verbose: false
  data:
    preprocess: true
    split_seed: 0
    idx: 30000
