# This workflows executes new or modified example notebooks.

name: test_single_notebook

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**/*.ipynb'
  pull_request:
    branches:
      - master
    paths:
      - 'examples/**/*.ipynb'

jobs:
  test_single_notebook:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup tmate debugging session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Check for new or changed .ipynb files
        id: changed-ipynb
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: |
            examples/*.ipynb

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.changed-ipynb.outputs.any_changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install --upgrade --upgrade-strategy eager -r requirements/dev.txt
          pip install --upgrade --upgrade-strategy eager -e .
          pip install --upgrade --upgrade-strategy-eager -e .[examples]
          pip install --upgrade --upgrade-strategy-eager -e .[ray]
          pip install --upgrade --upgrade-strategy eager -e .[shap]
          python -m spacy download en_core_web_md
          pip freeze
      - name: Run notebooks
        if: steps.changed-ipynb.outputs.any_changed == 'true'
        run: |
          pytest --nbmake `echo ${{ steps.changed-ipynb.outputs.all_modified_files }}`
#          for file in "${{ steps.changed-ipynb.outputs.all_modified_files }}"; do
#            python testing/test_notebooks.py $file
#          done
